/**
 * LLM-Agent Persona System
 *
 * Instead of hardcoded multipliers, personas are natural language descriptions.
 * Claude generates response profiles for each persona × task combination.
 * This follows the Stanford HAI approach: "Using LLMs to Simulate Multiple Humans."
 *
 * Architecture:
 *   1. User describes a population ("65-year-old retirees from rural areas")
 *   2. Claude generates a behavioral profile for that population on a specific task
 *   3. The simulation engine uses that profile + noise for individual differences
 *
 * This is generalizable to ANY experiment — not limited to predefined personas.
 */

export interface AgentPersonaConfig {
  id: string;
  description: string;  // free-text: "college students at a state university, ages 18-22"
  // Generated by Claude:
  profile?: GeneratedProfile;
}

export interface GeneratedProfile {
  // Behavioral tasks
  expectedRtMultiplier: number;     // 1.0 = baseline
  expectedAccuracyOffset: number;   // 0.0 = baseline
  variability: number;              // 1.0 = baseline
  fatigueRate: number;              // 0.0 to 0.5
  attentionLapseRate: number;       // 0.0 to 0.15
  // Survey tasks
  acquiescenceBias: number;         // 0.0 to 0.4
  extremeResponseStyle: number;     // 0.0 to 0.4
  // Cognitive factors (relative to college student baseline)
  cognitiveProfile: {
    g: number;              // -1 to 1
    spatial: number;        // -1 to 1
    workingMemory: number;  // -1 to 1
    inhibition: number;     // -1 to 1
  };
  // Explanation from Claude
  rationale: string;
}

const PROFILE_PROMPT = `You generate realistic behavioral profiles for simulated experiment participants.

Given a population description and task, estimate how this population would perform relative to a baseline of college students (ages 18-22, no clinical conditions).

Return ONLY valid JSON:
{
  "expectedRtMultiplier": number (1.0 = baseline, >1 = slower, <1 = faster),
  "expectedAccuracyOffset": number (0.0 = baseline, negative = less accurate),
  "variability": number (1.0 = baseline, >1 = more variable),
  "fatigueRate": number (0.0 to 0.5, higher = faster fatigue),
  "attentionLapseRate": number (0.0 to 0.15, probability of random responding),
  "acquiescenceBias": number (0.0 to 0.4, tendency to agree on surveys),
  "extremeResponseStyle": number (0.0 to 0.4, tendency to use scale endpoints),
  "cognitiveProfile": {
    "g": number (-1 to 1, general intelligence relative to college students),
    "spatial": number (-1 to 1, spatial ability),
    "workingMemory": number (-1 to 1, working memory capacity),
    "inhibition": number (-1 to 1, inhibitory control)
  },
  "rationale": "1-2 sentences explaining your estimates based on psychology literature"
}

Be specific and grounded in behavioral science. For example:
- Older adults: slower RT (1.3-1.5x), intact accuracy on easy tasks, higher fatigue, strong acquiescence
- Children 8-12: faster but less accurate, high variability, frequent lapses, extreme responding
- MTurk workers: slightly faster (familiar with online tasks), moderate satisficing
- Clinical ADHD: normal speed, high variability, very high lapse rate

Return ONLY JSON.`;

/**
 * Generate a behavioral profile for a custom persona description.
 * Makes one Claude API call per persona.
 */
export async function generatePersonaProfile(
  description: string,
  taskDescription: string,
): Promise<GeneratedProfile> {
  try {
    const res = await fetch('/api/claude', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 500,
        system: PROFILE_PROMPT,
        messages: [{
          role: 'user',
          content: `Population: "${description}"\nTask context: "${taskDescription}"\nGenerate a behavioral profile.`,
        }],
      }),
    });

    if (!res.ok) throw new Error(`${res.status}`);
    const data = await res.json();
    const raw = data.content?.[0]?.text ?? '';
    const cleaned = raw.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
    return JSON.parse(cleaned) as GeneratedProfile;
  } catch {
    // Fallback: college student baseline
    return {
      expectedRtMultiplier: 1.0,
      expectedAccuracyOffset: 0.0,
      variability: 1.0,
      fatigueRate: 0.15,
      attentionLapseRate: 0.02,
      acquiescenceBias: 0.1,
      extremeResponseStyle: 0.05,
      cognitiveProfile: { g: 0, spatial: 0, workingMemory: 0, inhibition: 0 },
      rationale: 'Baseline college student profile (fallback).',
    };
  }
}

/**
 * Convert a GeneratedProfile to a PersonaDefinition (for use with existing simulation).
 */
export function profileToPersona(id: string, name: string, profile: GeneratedProfile): import('./types').PersonaDefinition {
  return {
    id,
    name,
    emoji: '🧑',
    description: profile.rationale,
    rtMultiplier: profile.expectedRtMultiplier,
    accuracyOffset: profile.expectedAccuracyOffset,
    variabilityMultiplier: profile.variability,
    fatigueRate: profile.fatigueRate,
    attentionLapseRate: profile.attentionLapseRate,
    acquiescenceBias: profile.acquiescenceBias,
    extremeResponseStyle: profile.extremeResponseStyle,
  };
}
